create-produccet:
	curl -X POST http://localhost:3000/products \
      -H "Content-Type: application/json" \
      -H "Idempotency-Key: 123e4567-e89b-12d3-a456-426614174000" \
      -d '{"name": "iPhone 15 Pro", "sku": "IPH15PRO"}'
