install:
	go install honnef.co/go/tools/cmd/staticcheck@latest
	go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
	go install golang.org/x/vuln/cmd/govulncheck@latest
	go install github.com/securego/gosec/v2/cmd/gosec@latest
	go install github.com/google/wire/cmd/wire@latest


lint:
	go vet ./...
	staticcheck ./...
	golangci-lint run ./...
	go test -race ./...
	govulncheck ./...
	gosec ./...

