version: "3.9"

services:
  redis:
    image: redis:7.2
    container_name: redis-secure
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: yourpassword
