// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	user3 "github.com/ciazhar/go-zhar/examples/scalable_system/l0/internal/controller/rest/user"
	"github.com/ciazhar/go-zhar/examples/scalable_system/l0/internal/repository/dummy/user"
	user2 "github.com/ciazhar/go-zhar/examples/scalable_system/l0/internal/service/user"
	"github.com/ciazhar/go-zhar/pkg/validator"
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

// Build the REST module given infra deps from main (validator + redis client).
func InitializeRESTModule(v validator.Validator, rdb *redis.Client) *RESTModule {
	userRepository := user.NewUserRepository()
	userService := user2.NewUserService(userRepository)
	userController := user3.NewUserController(userService)
	restModule := NewRESTModule(v, rdb, userController)
	return restModule
}

// wire.go:

// Provider set for the user stack
var userSet = wire.NewSet(user.NewUserRepository, user2.NewUserService, user3.NewUserController)
