// Code generated by MockGen. DO NOT EDIT.
// Source: ./examples/scalable_system/l0/internal/service/user/contract.go
//
// Generated by this command:
//
//	mockgen -source=./examples/scalable_system/l0/internal/service/user/contract.go -destination=./examples/scalable_system/l0/internal/service/user/mock/mock_contract.go
//

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	reflect "reflect"

	request "github.com/ciazhar/go-zhar-scalable-system-l0/internal/model/request"
	response "github.com/ciazhar/go-zhar-scalable-system-l0/internal/model/response"
	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserService) CreateUser(ctx context.Context, req request.CreateUserBodyRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceMockRecorder) CreateUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserService)(nil).CreateUser), ctx, req)
}

// GetUserByID mocks base method.
func (m *MockUserService) GetUserByID(ctx context.Context, id string) (*response.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*response.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserServiceMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserService)(nil).GetUserByID), ctx, id)
}

// GetUsersWithPagination mocks base method.
func (m *MockUserService) GetUsersWithPagination(ctx context.Context, page, limit int) ([]response.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersWithPagination", ctx, page, limit)
	ret0, _ := ret[0].([]response.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUsersWithPagination indicates an expected call of GetUsersWithPagination.
func (mr *MockUserServiceMockRecorder) GetUsersWithPagination(ctx, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersWithPagination", reflect.TypeOf((*MockUserService)(nil).GetUsersWithPagination), ctx, page, limit)
}

// IsUserExistsByEmail mocks base method.
func (m *MockUserService) IsUserExistsByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserExistsByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserExistsByEmail indicates an expected call of IsUserExistsByEmail.
func (mr *MockUserServiceMockRecorder) IsUserExistsByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserExistsByEmail", reflect.TypeOf((*MockUserService)(nil).IsUserExistsByEmail), ctx, email)
}

// SoftDeleteUser mocks base method.
func (m *MockUserService) SoftDeleteUser(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteUser indicates an expected call of SoftDeleteUser.
func (mr *MockUserServiceMockRecorder) SoftDeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteUser", reflect.TypeOf((*MockUserService)(nil).SoftDeleteUser), ctx, id)
}

// UpdateUser mocks base method.
func (m *MockUserService) UpdateUser(ctx context.Context, id string, req request.UpdateUserBodyRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserServiceMockRecorder) UpdateUser(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserService)(nil).UpdateUser), ctx, id, req)
}

// UpsertUserByID mocks base method.
func (m *MockUserService) UpsertUserByID(ctx context.Context, req request.UpsertUserBodyRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserByID", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserByID indicates an expected call of UpsertUserByID.
func (mr *MockUserServiceMockRecorder) UpsertUserByID(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserByID", reflect.TypeOf((*MockUserService)(nil).UpsertUserByID), ctx, req)
}
