package main

import (
	_ "github.com/ciazhar/go-zhar/examples/fiber/swagger/api/swagger" // docs is generated by Swag CLI, you have to import it.
	"github.com/ciazhar/go-zhar/examples/fiber/swagger/internal/user"
	"github.com/ciazhar/go-zhar/pkg/env"
	"github.com/ciazhar/go-zhar/pkg/logger"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/swagger"
	"github.com/spf13/viper"
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host 127.0.0.1:3000
// @BasePath /
func main() {
	log := logger.Init(logger.Config{
		ConsoleLoggingEnabled: true,
	})
	env.Init("config.json", log)

	app := fiber.New()

	user.Init(app)
	app.Get("/swagger/*", swagger.HandlerDefault) // default

	err := app.Listen(":" + viper.GetString("application.port"))
	if err != nil {
		log.Fatalf("fiber failed to start : %v", err)
	}
}
